//
//  StoryDetailsConfigurator.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 26.04.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class StoryDetailsConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = StoryDetailsConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: StoryDetailsViewController)
  {
    let router = StoryDetailsRouter()
    router.viewController = viewController
    
    let presenter = StoryDetailsPresenter()
    presenter.output = viewController
    
    let interactor = StoryDetailsInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
