//
//  StoryDetailsModels.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 26.04.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct StoryDetails
{
    struct Present
    {
        struct Model
        {
            let story: Story
        }
        struct ViewModel
        {
            let title: String
            let description: String
        }
    }
    
    struct UpdateImage
    {
        struct Model
        {
            let image: Image
        }
        
        struct ViewModel {
            let url: URL
            let title: String
        }
    }
}
