//
//  StoryDetailsInteractor.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 26.04.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol StoryDetailsModelBoundary
{
    func presentDetails(model: StoryDetails.Present.Model)
    func presentImage(model: StoryDetails.UpdateImage.Model)
}

class StoryDetailsInteractor: StoryDetailsRequestBoundary
{
    var output: StoryDetailsModelBoundary!
    
    var story: Story!
    
    var storage: Store!
    
    func fetchPoints(){
        let worker = FetchPointsWorker(storyId:story.id, storage:storage)
        worker.fetchPoints { [weak self](points, error) in
          //  self?.story.set(points: points)
            self?.output.presentDetails(model: StoryDetails.Present.Model(story: (self?.story)!))
            
            self?.fetchMainImage()
        }
    }
    //TODO - rewrite
    func fetchMainImage(){
//        if let firstPoint = story.points.first?.model,
//            let firstImageId = firstPoint.images.first?.id {
//            let worker = FetchImageWorker(id: firstImageId , storage: storage)
//            worker.fetchImage({ [weak self](image,error) in
//                self?.story.points[0].model?.updateImage(image: image, id: firstImageId)
//                self?.output.presentImage(model: StoryDetails.UpdateImage.Model(image: image))
//            })
//        }
        
    }
  // MARK: - Business logic
  
}
