//
//  StoryDetailsViewController.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 26.04.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import MapKit
import ImageSlideshow

protocol StoryDetailsRequestBoundary
{
    var storage : Store! { get set }
    var story: Story! { get set }
    func fetchPoints()
}

class StoryDetailsViewController: UIViewController, StoryDetailsViewModelBoundary
{
    var output: StoryDetailsRequestBoundary!
    var router: StoryDetailsRouter!
  
    
    @IBOutlet weak var mainImageView: UIImageView!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var mapView: MKMapView!
    @IBOutlet weak var slideShow: ImageSlideshow!
    
    
  // MARK: - Object lifecycle
  
    override func awakeFromNib()
    {
        super.awakeFromNib()
        StoryDetailsConfigurator.sharedInstance.configure(viewController: self)
    }
  
    override func viewDidLoad() {
        output.fetchPoints()
    }
    
  // MARK: - Event handling
  
  
  // MARK: - Display logic
  
    func display(titleAndDescription: StoryDetails.Present.ViewModel) {
        self.title = titleAndDescription.title
        self.descriptionLabel.text = titleAndDescription.description
    }
    
    func display(image: StoryDetails.UpdateImage.ViewModel) {
        mainImageView.kf.setImage(with: image.url)
    }
}
