//
//  StoryDetailsPresenter.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 26.04.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol StoryDetailsViewModelBoundary: class
{
  func displaySomething(viewModel: StoryDetails.Something.ViewModel)
}

class StoryDetailsPresenter: StoryDetailsResponseBoundary
{
  weak var output: StoryDetailsViewModelBoundary!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: StoryDetails.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = StoryDetails.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
