//
//  StoryDetailsPresenter.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 26.04.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol StoryDetailsViewModelBoundary: class
{
    func display(titleAndDescription: StoryDetails.Present.ViewModel)
    func display(image: StoryDetails.UpdateImage.ViewModel)
}

class StoryDetailsPresenter: StoryDetailsModelBoundary
{
    weak var output: StoryDetailsViewModelBoundary!
  
    // MARK: - Presentation logic

    func presentDetails(model: StoryDetails.Present.Model)
    {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let story = model.story
        let viewModel = StoryDetails.Present.ViewModel(title: story.title, description: story.description)
        output.display(titleAndDescription: viewModel)
    }
    
    func presentImage(model: StoryDetails.UpdateImage.Model) {
        let image = model.image
        output.display(image: StoryDetails.UpdateImage.ViewModel(url: image.url, title: image.title))
    }
}
