//
//  FetchStoriesWorker.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 10.02.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation




class FetchStoriesWorker
{
    let storage : Store
    init(storage : Store) {
        self.storage = storage
    }
  // MARK: - Business Logic
    func fetchStories(completionHandler: @escaping (_ stories:[Story]) -> ()){
        storage.fetchStories(){ (stories,error) in
            if error == nil {
                completionHandler(stories)
            }
            else {
             completionHandler([])   
            }
        }
    }
}
