//
//  StoryListInteractor.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 10.02.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import CoreLocation

protocol StoryListResponseBoundary
{
    func responded(storyList: StoryList.Response)
}

class StoryListInteractor: StoryListRequestBoundary
{
    let storage: Store

    var output: StoryListResponseBoundary!
    var worker: FetchStoriesWorker!
  
    var stories : [Story]! {
        didSet {
            output.responded(storyList: StoryList.Response(stories: stories))
        }
    }

    init(storage: Store) {
        self.storage = storage
    }
    
    
  // MARK: - Business logic
  
    func fetchStories() {
    
    worker = FetchStoriesWorker(storage: storage)
        worker.fetchStories(completionHandler: { stories in
            self.stories = stories
        })
    }
    
    internal func story(row: Int) -> Story {
        return stories[row]
    }

}
