//
//  StoryListRouter.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 10.02.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol StoriesListRouterInput
{
  func navigateToStoryDetails()
}

class StoryListRouter: StoriesListRouterInput
{
  weak var viewController: StoryListViewController!
  
  // MARK: - Navigation
  
    func navigateToStoryDetails()
  {
    viewController.performSegue(withIdentifier: "ShowStoryDetailsScene", sender: nil)
  }
  
  // MARK: - Communication
  
  func passDataToNextScene(segue: UIStoryboardSegue)
  {
    // NOTE: Teach the router which scenes it can communicate with
    
    if segue.identifier == "ShowStoryDetailsScene" {
      passDataToStoryDetailsScene(segue: segue)
    }
  }
  
  func passDataToStoryDetailsScene(segue: UIStoryboardSegue)
  {
    let storyDetailsViewController = segue.destination as! StoryDetailsViewController
    storyDetailsViewController.output.storage = viewController.output.storage
    storyDetailsViewController.output.story = viewController.output.story(row: (viewController.tableView.indexPathForSelectedRow?.row)!)
    
  }
}
