//
//  StoryListConfigurator.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 10.02.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension StoryListViewController
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

class StoryListConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = StoryListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: StoryListViewController)
  {
    let router = StoryListRouter()
    router.viewController = viewController
    
    let presenter = StoryListPresenter()
    presenter.output = viewController
    
    let interactor = StoryListInteractor(storage: APIStore())
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
