//
//  StoryListPresenter.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 10.02.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol StoryListViewModelBoundary: class
{
    func display(stories: [StoryList.ViewModel.Story])
}

class StoryListPresenter: StoryListResponseBoundary
{

  weak var output: StoryListViewModelBoundary!
  
  // MARK: - Presentation logic
    
    func responded(storyList: StoryList.Response) {
//        output.display(stories: storyList.stories.map({ StoryList.ViewModel.Story(title: $0.title, description: $0.description, duration: "\($0.duration.hours):\($0.duration.minutes)", numberOfPoints: String($0.points.count) )
//            
//        }))
    }
}
