//
//  StoryListModels.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 10.02.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import CoreLocation

struct Camera {
    let centerPoint: CLLocationCoordinate2D
    let distance: CLLocationDistance
    let pitch : CGFloat
    let heading : CLLocationDirection
}


struct StoryList
{

    struct Response
    {
        let stories : [Story]
    }
    struct ViewModel
    {
        struct Story {
            let title : String
            let description : String
            let duration : String
            let numberOfPoints : String
        }
    }
}
