//
//  StoryListViewController.swift
//  poznaj-app-ios
//
//  Created by Daniel Stokowski on 10.02.2017.
//  Copyright (c) 2017 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import MapKit

protocol StoryListRequestBoundary
{
    var storage : Store { get }
    
    func fetchStories()
    func story(row:Int) -> Story
}

class StoryListViewController: UITableViewController, StoryListViewModelBoundary
{
    var output: StoryListRequestBoundary!
    var router: StoryListRouter!

    //
    var stories : [StoryList.ViewModel.Story] = [] {
        didSet {
            tableView.reloadData()
        }
    }
    
    //UI
    
    // MARK: - Object lifecycle

    override func awakeFromNib()
    {
    super.awakeFromNib()
        StoryListConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        tableView.rowHeight = UITableViewAutomaticDimension
        tableView.estimatedRowHeight = 207.0;
        
        viewLoaded()
    }

    // MARK: - Event handling

    func viewLoaded()
    {
        output.fetchStories()
    }

    // MARK: - Display logic
    
    func display(stories: [StoryList.ViewModel.Story]) {
        self.stories = stories
    }
    
    // MARK: - UITableViewDelegate
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return stories.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "StoryID") as? StoryListCell
        
        let model = stories[indexPath.row]
        
        cell?.title.text = model.title
        cell?.aDescription.text = model.description
        cell?.duration.text = model.duration
        cell?.numberOfPoints.text = model.numberOfPoints
        
        return cell ?? UITableViewCell()
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        router.navigateToStoryDetails()
    }
}
